-- REMINDER THAT WHEN YOU CREATE ON APEX PLEASE DROP THE OLD TABLE THEN RUN THIS SCRIPT

CREATE TABLE ORARENT_CUSTOMERS 
  (CUSTOMER_ID NUMBER(10) NOT NULL, 
   LAST_NAME VARCHAR2(25) NOT NULL,
   FIRST_NAME VARCHAR2(25) NOT NULL, 
   HOME_PHONE VARCHAR2(12) NOT NULL,
   ADDRESS VARCHAR2(100) NOT NULL, 
   CITY VARCHAR2(30) NOT NULL,
   STATE VARCHAR2(2) NOT NULL, 
   EMAIL VARCHAR2(25),
   CELL_PHONE VARCHAR2(12),
   CONSTRAINT customers_customer_id_pk PRIMARY KEY(CUSTOMER_ID)
);

