-- REMINDER THAT WHEN YOU CREATE ON APEX PLEASE DROP THE OLD TABLE THEN RUN THIS SCRIPT

CREATE TABLE ORARENT_CUSTOMERS 
  (CUSTOMER_ID NUMBER(10) NOT NULL, 
   LAST_NAME VARCHAR2(25) NOT NULL,
   FIRST_NAME VARCHAR2(25) NOT NULL, 
   HOME_PHONE VARCHAR2(12) NOT NULL,
   ADDRESS VARCHAR2(100) NOT NULL, 
   CITY VARCHAR2(30) NOT NULL,
   STATE VARCHAR2(2) NOT NULL, 
   EMAIL VARCHAR2(25),
   CELL_PHONE VARCHAR2(12),
   CONSTRAINT customers_customer_id_pk PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE ORARENT_MOVIES
  ( TITLE_ID NUMBER(10), 
    TITLE VARCHAR2(60) NOT NULL, 
    DESCRIPTION VARCHAR2(400) NOT NULL, 
    RATING VARCHAR2(4), 
    CATEGORY VARCHAR2(20),
    RELEASE_DATE DATE NOT NULL, 
    CONSTRAINT movies_title_id_pk PRIMARY KEY(TITLE_ID),
    CONSTRAINT movies_rating_check CHECK(RATING IN ('G', 'PG', 'PG13', 'R')),
    CONSTRAINT movies_category_check CHECK(CATEGORY IN ('DRAMA', 'COMEDY', 'ACTION', 'CHILD', 'SCIFI', 'DOCUMENTARY'))
);
